#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Aug 15 11:53:26 -05 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_simple_alu_behav -key {Behavioral:sim_1:Functional:tb_simple_alu} -tclbatch tb_simple_alu.tcl -view /home/jamm/PDS/TP1_EJ1_P1/tb_simple_alu_behav.wcfg -log simulate.log"
xsim tb_simple_alu_behav -key {Behavioral:sim_1:Functional:tb_simple_alu} -tclbatch tb_simple_alu.tcl -view /home/jamm/PDS/TP1_EJ1_P1/tb_simple_alu_behav.wcfg -log simulate.log

