webtalk_init -webtalk_dir /home/jamm/PDS/TP1_EJ2/TP1_EJ2.sim/sim_1/behav/xsim/xsim.dir/tb_conv_encoder_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Aug 15 13:11:51 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3f9f77657e245abd9f0299ebacb42d01" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1a78e326425f4a4994c0a1ad1103ce70" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "211" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1628.512 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "133992_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3946240657 -regid "" -xml /home/jamm/PDS/TP1_EJ2/TP1_EJ2.sim/sim_1/behav/xsim/xsim.dir/tb_conv_encoder_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jamm/PDS/TP1_EJ2/TP1_EJ2.sim/sim_1/behav/xsim/xsim.dir/tb_conv_encoder_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jamm/PDS/TP1_EJ2/TP1_EJ2.sim/sim_1/behav/xsim/xsim.dir/tb_conv_encoder_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
