#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Aug 18 11:00:06 -05 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 984dbbfc90644e279005344ea58e7cb2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_diff_ecuation_behav xil_defaultlib.tb_diff_ecuation -log elaborate.log"
xelab -wto 984dbbfc90644e279005344ea58e7cb2 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_diff_ecuation_behav xil_defaultlib.tb_diff_ecuation -log elaborate.log

