#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Aug 18 11:00:07 -05 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_diff_ecuation_behav -key {Behavioral:sim_1:Functional:tb_diff_ecuation} -tclbatch tb_diff_ecuation.tcl -view /home/jamm/PDS/TP1_EJ3/tb_diff_ecuation_behav.wcfg -log simulate.log"
xsim tb_diff_ecuation_behav -key {Behavioral:sim_1:Functional:tb_diff_ecuation} -tclbatch tb_diff_ecuation.tcl -view /home/jamm/PDS/TP1_EJ3/tb_diff_ecuation_behav.wcfg -log simulate.log

