#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Aug 15 12:13:34 -05 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 8a3b8ef188cf432897183b0d9f5d41f5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_ripple_carry_adder_behav xil_defaultlib.tb_ripple_carry_adder -log elaborate.log"
xelab -wto 8a3b8ef188cf432897183b0d9f5d41f5 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_ripple_carry_adder_behav xil_defaultlib.tb_ripple_carry_adder -log elaborate.log

