#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Aug 15 12:47:54 -05 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 1a78e326425f4a4994c0a1ad1103ce70 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_conv_encoder_behav xil_defaultlib.tb_conv_encoder -log elaborate.log"
xelab -wto 1a78e326425f4a4994c0a1ad1103ce70 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_conv_encoder_behav xil_defaultlib.tb_conv_encoder -log elaborate.log

