#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Aug 15 12:47:56 -05 2020
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_conv_encoder_behav -key {Behavioral:sim_1:Functional:tb_conv_encoder} -tclbatch tb_conv_encoder.tcl -view /home/jamm/PDS/TP1_EJ2/conv_encoder_behav.wcfg -log simulate.log"
xsim tb_conv_encoder_behav -key {Behavioral:sim_1:Functional:tb_conv_encoder} -tclbatch tb_conv_encoder.tcl -view /home/jamm/PDS/TP1_EJ2/conv_encoder_behav.wcfg -log simulate.log

